name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello and welcome to **Install.js**! Thank you for your first issue, it helps us improve the library!"
        pr-message: "Hello and welcome to **Install.js**! Thank you for your first pull request, it helps us improve the library!"
